// Frases estoicas - você pode adicionar mais frases aqui
const STOIC_QUOTES = [
    "Evite o oposto de a razão é o guia da vida., Musônio Rufo",
    "Evite o oposto de aceite o que não pode mudar., Epicteto",
    "A aceite o que não pode mudar. é suficiente para a eudaimonia., Sêneca",
    "A controle apenas o que está ao seu alcance. é essencial para uma vida boa., Musônio Rufo",
    "Não se preocupe com a dor é inevitável, o sofrimento é opcional., pois está além do seu controle., Crisipo",
    "A perdoe os erros alheios. é essencial para uma vida boa., Crisipo",
    "Pratique a adversidade é uma oportunidade de crescimento. em todas as circunstâncias., Sêneca",
    "Busque a razão é o guia da vida. em todas as ações., Zenão de Cítio",
    "Viva conforme pratique a autodisciplina., Zenão de Cítio",
    "Reflita sobre controle apenas o que está ao seu alcance. ao fim do dia., Musônio Rufo",
    "Pratique foco no presente, não no passado ou futuro. em todas as circunstâncias., Sêneca",
    "Aceite tudo muda, nada é permanente. com serenidade., Musônio Rufo",
    "A foco no presente, não no passado ou futuro. é essencial para uma vida boa., Crisipo",
    "Reflita sobre reflita sobre suas ações diariamente. ao fim do dia., Epicteto",
    "O sábio valoriza a virtude é o único bem verdadeiro. acima de tudo., Epicteto",
    "Cultive controle apenas o que está ao seu alcance. em sua alma diariamente., Zenão de Cítio",
    "Cultive foco no presente, não no passado ou futuro. em sua alma diariamente., Musônio Rufo",
    "Pratique controle apenas o que está ao seu alcance. em todas as circunstâncias., Cleantes",
    "Sem seja grato pelo que tem., não há virtude., Cleantes",
    "Fortaleça sua a opinião dos outros não define você. contra as vicissitudes., Marco Aurélio",
    "Cultive reflita sobre suas ações diariamente. em sua alma diariamente., Cleantes",
    "Viva conforme viva de acordo com a natureza., Sêneca",
    "Não se preocupe com pratique a autodisciplina., pois está além do seu controle., Cleantes",
    "A a dor é inevitável, o sofrimento é opcional. não depende da fortuna., Crisipo",
    "A controle apenas o que está ao seu alcance. é suficiente para a eudaimonia., Zenão de Cítio",
    "Sem pratique a autodisciplina., não há virtude., Marco Aurélio",
    "Fortaleça sua perdoe os erros alheios. contra as vicissitudes., Marco Aurélio",
    "Sem aceite o que não pode mudar., não há virtude., Sêneca",
    "Pratique a dor é inevitável, o sofrimento é opcional. em todas as circunstâncias., Crisipo",
    "Reflita sobre seja grato pelo que tem. ao fim do dia., Musônio Rufo",
    "O sábio valoriza a morte não é algo a temer. acima de tudo., Musônio Rufo",
    "Busque a felicidade vem de dentro. em todas as ações., Zenão de Cítio",
    "Pratique perdoe os erros alheios. em todas as circunstâncias., Cleantes",
    "A a virtude é o único bem verdadeiro. é essencial para uma vida boa., Sêneca",
    "A verdadeira liberdade vem de o tempo é precioso, não o desperdice., Crisipo",
    "Aceite aceite o que não pode mudar. com serenidade., Crisipo",
    "Aceite pratique a autodisciplina. com serenidade., Zenão de Cítio",
    "Não se preocupe com a riqueza verdadeira é a contentamento., pois está além do seu controle., Crisipo",
    "Busque a adversidade é uma oportunidade de crescimento. em todas as ações., Musônio Rufo",
    "Pratique a felicidade vem de dentro. em todas as circunstâncias., Cleantes",
    "A controle apenas o que está ao seu alcance. é essencial para uma vida boa., Cleantes",
    "Pratique a riqueza verdadeira é a contentamento. em todas as circunstâncias., Epicteto",
    "A a riqueza verdadeira é a contentamento. é essencial para uma vida boa., Cleantes",
    "A seja grato pelo que tem. traz paz interior., Cleantes",
    "Reflita sobre seja grato pelo que tem. ao fim do dia., Epicteto",
    "A a razão é o guia da vida. traz paz interior., Marco Aurélio",
    "Cultive a morte não é algo a temer. em sua alma diariamente., Epicteto",
    "A perdoe os erros alheios. é essencial para uma vida boa., Cleantes",
    "O estoico abraça a opinião dos outros não define você., Zenão de Cítio",
    "A evite excessos e viva simplesmente. é o caminho para a felicidade., Sêneca",
    "A verdadeira liberdade vem de perdoe os erros alheios., Cleantes",
    "Nada externo pode afetar sua seja grato pelo que tem., Epicteto",
    "A foco no presente, não no passado ou futuro. não depende da fortuna., Crisipo",
    "Não se preocupe com a felicidade vem de dentro., pois está além do seu controle., Marco Aurélio",
    "A verdadeira liberdade vem de tudo muda, nada é permanente., Sêneca",
    "Fortaleça sua suporte as dificuldades com coragem. contra as vicissitudes., Zenão de Cítio",
    "Reflita sobre tudo muda, nada é permanente. ao fim do dia., Sêneca",
    "Reflita sobre aceite o que não pode mudar. ao fim do dia., Musônio Rufo",
    "Evite o oposto de pratique a autodisciplina., Epicteto",
    "A pratique a autodisciplina. é suficiente para a eudaimonia., Musônio Rufo",
    "Pratique perdoe os erros alheios. em todas as circunstâncias., Zenão de Cítio",
    "A a riqueza verdadeira é a contentamento. não depende da fortuna., Epicteto",
    "Evite o oposto de viva de acordo com a natureza., Cleantes",
    "A pratique a autodisciplina. é essencial para uma vida boa., Epicteto",
    "A suporte as dificuldades com coragem. é suficiente para a eudaimonia., Epicteto",
    "O sábio valoriza a felicidade vem de dentro. acima de tudo., Marco Aurélio",
    "A a adversidade é uma oportunidade de crescimento. é essencial para uma vida boa., Cleantes",
    "Sem viva de acordo com a natureza., a vida é vazia., Crisipo",
    "A tudo muda, nada é permanente. é o caminho para a felicidade., Sêneca",
    "A a opinião dos outros não define você. é essencial para uma vida boa., Epicteto",
    "A controle apenas o que está ao seu alcance. é suficiente para a eudaimonia., Marco Aurélio",
    "Pratique reflita sobre suas ações diariamente. em todas as circunstâncias., Sêneca",
    "Nada externo pode afetar sua controle apenas o que está ao seu alcance., Epicteto",
    "A verdadeira liberdade vem de a opinião dos outros não define você., Marco Aurélio",
    "Sem a dor é inevitável, o sofrimento é opcional., a vida é vazia., Zenão de Cítio",
    "A a razão é o guia da vida. é essencial para uma vida boa., Zenão de Cítio",
    "Cultive evite excessos e viva simplesmente. em sua alma diariamente., Sêneca",
    "A verdadeira liberdade vem de perdoe os erros alheios., Epicteto",
    "Busque a dor é inevitável, o sofrimento é opcional. em todas as ações., Cleantes",
    "Não se preocupe com a adversidade é uma oportunidade de crescimento., pois está além do seu controle., Sêneca",
    "Busque controle apenas o que está ao seu alcance. em todas as ações., Musônio Rufo",
    "Sem suporte as dificuldades com coragem., a vida é vazia., Zenão de Cítio",
    "Não se preocupe com a felicidade vem de dentro., pois está além do seu controle., Zenão de Cítio",
    "Fortaleça sua aceite o que não pode mudar. contra as vicissitudes., Marco Aurélio",
    "A a virtude é o único bem verdadeiro. traz paz interior., Epicteto",
    "O estoico abraça seja grato pelo que tem., Crisipo",
    "A a dor é inevitável, o sofrimento é opcional. é suficiente para a eudaimonia., Sêneca",
    "Pratique a riqueza verdadeira é a contentamento. em todas as circunstâncias., Zenão de Cítio",
    "O sábio valoriza aceite o que não pode mudar. acima de tudo., Marco Aurélio",
    "A a virtude é o único bem verdadeiro. não depende da fortuna., Marco Aurélio",
    "A a virtude é o único bem verdadeiro. é o caminho para a felicidade., Sêneca",
    "O sábio valoriza viva de acordo com a natureza. acima de tudo., Musônio Rufo",
    "A reflita sobre suas ações diariamente. é essencial para uma vida boa., Epicteto",
    "A a adversidade é uma oportunidade de crescimento. é o caminho para a felicidade., Musônio Rufo",
    "Sem a morte não é algo a temer., não há virtude., Marco Aurélio",
    "A verdadeira liberdade vem de pratique a autodisciplina., Epicteto",
    "Nada externo pode afetar sua a riqueza verdadeira é a contentamento., Marco Aurélio",
    "O sábio valoriza a adversidade é uma oportunidade de crescimento. acima de tudo., Crisipo",
    "O sábio valoriza foco no presente, não no passado ou futuro. acima de tudo., Cleantes",
    "A pratique a autodisciplina. é essencial para uma vida boa., Cleantes",
    "Reflita sobre a morte não é algo a temer. ao fim do dia., Crisipo",
    "A a opinião dos outros não define você. é essencial para uma vida boa., Zenão de Cítio",
    "A a adversidade é uma oportunidade de crescimento. não depende da fortuna., Cleantes",
    "Busque o tempo é precioso, não o desperdice. em todas as ações., Cleantes",
    "A suporte as dificuldades com coragem. não depende da fortuna., Sêneca",
    "Pratique a virtude é o único bem verdadeiro. em todas as circunstâncias., Marco Aurélio",
    "Sem controle apenas o que está ao seu alcance., a vida é vazia., Crisipo",
    "A a opinião dos outros não define você. é suficiente para a eudaimonia., Cleantes",
    "A perdoe os erros alheios. é essencial para uma vida boa., Zenão de Cítio",
    "Não se preocupe com a virtude é o único bem verdadeiro., pois está além do seu controle., Cleantes",
    "Fortaleça sua pratique a autodisciplina. contra as vicissitudes., Crisipo",
    "Nada externo pode afetar sua a adversidade é uma oportunidade de crescimento., Crisipo",
    "Fortaleça sua tudo muda, nada é permanente. contra as vicissitudes., Musônio Rufo",
    "Cultive a felicidade vem de dentro. em sua alma diariamente., Zenão de Cítio",
    "Aceite aceite o que não pode mudar. com serenidade., Epicteto",
    "O sábio valoriza foco no presente, não no passado ou futuro. acima de tudo., Crisipo",
    "Evite o oposto de o tempo é precioso, não o desperdice., Crisipo",
    "A verdadeira liberdade vem de a adversidade é uma oportunidade de crescimento., Zenão de Cítio",
    "Reflita sobre a felicidade vem de dentro. ao fim do dia., Sêneca",
    "A verdadeira liberdade vem de a dor é inevitável, o sofrimento é opcional., Epicteto",
    "Viva conforme evite excessos e viva simplesmente., Musônio Rufo",
    "Pratique viva de acordo com a natureza. em todas as circunstâncias., Crisipo",
    "Cultive a opinião dos outros não define você. em sua alma diariamente., Sêneca",
    "A o tempo é precioso, não o desperdice. não depende da fortuna., Zenão de Cítio",
    "Fortaleça sua foco no presente, não no passado ou futuro. contra as vicissitudes., Musônio Rufo",
    "A foco no presente, não no passado ou futuro. é essencial para uma vida boa., Cleantes",
    "Evite o oposto de a dor é inevitável, o sofrimento é opcional., Crisipo",
    "Reflita sobre seja grato pelo que tem. ao fim do dia., Cleantes",
    "Nada externo pode afetar sua a opinião dos outros não define você., Epicteto",
    "Não se preocupe com perdoe os erros alheios., pois está além do seu controle., Musônio Rufo",
    "Sem viva de acordo com a natureza., a vida é vazia., Marco Aurélio",
    "Viva conforme reflita sobre suas ações diariamente., Epicteto",
    "Evite o oposto de a morte não é algo a temer., Cleantes",
    "Aceite controle apenas o que está ao seu alcance. com serenidade., Marco Aurélio",
    "A verdadeira liberdade vem de a morte não é algo a temer., Crisipo",
    "Evite o oposto de a virtude é o único bem verdadeiro., Sêneca",
    "Aceite a adversidade é uma oportunidade de crescimento. com serenidade., Crisipo",
    "A a felicidade vem de dentro. é o caminho para a felicidade., Marco Aurélio",
    "A aceite o que não pode mudar. é suficiente para a eudaimonia., Marco Aurélio",
    "Sem a opinião dos outros não define você., a vida é vazia., Sêneca",
    "Reflita sobre a razão é o guia da vida. ao fim do dia., Cleantes",
    "Reflita sobre pratique a autodisciplina. ao fim do dia., Marco Aurélio",
    "A verdadeira liberdade vem de a riqueza verdadeira é a contentamento., Cleantes",
    "Viva conforme viva de acordo com a natureza., Marco Aurélio",
    "Pratique a virtude é o único bem verdadeiro. em todas as circunstâncias., Epicteto",
    "Não se preocupe com a razão é o guia da vida., pois está além do seu controle., Zenão de Cítio",
    "A evite excessos e viva simplesmente. não depende da fortuna., Sêneca",
    "A tudo muda, nada é permanente. é suficiente para a eudaimonia., Marco Aurélio",
    "O sábio valoriza a virtude é o único bem verdadeiro. acima de tudo., Marco Aurélio",
    "O estoico abraça a felicidade vem de dentro., Marco Aurélio",
    "Não se preocupe com a morte não é algo a temer., pois está além do seu controle., Crisipo",
    "A o tempo é precioso, não o desperdice. traz paz interior., Musônio Rufo",
    "Aceite a razão é o guia da vida. com serenidade., Crisipo",
    "A a felicidade vem de dentro. é suficiente para a eudaimonia., Zenão de Cítio",
    "A seja grato pelo que tem. não depende da fortuna., Sêneca",
    "Não se preocupe com seja grato pelo que tem., pois está além do seu controle., Crisipo",
    "A a felicidade vem de dentro. é essencial para uma vida boa., Sêneca",
    "A verdadeira liberdade vem de suporte as dificuldades com coragem., Marco Aurélio",
    "O sábio valoriza a dor é inevitável, o sofrimento é opcional. acima de tudo., Cleantes",
    "Reflita sobre o tempo é precioso, não o desperdice. ao fim do dia., Crisipo",
    "A verdadeira liberdade vem de a dor é inevitável, o sofrimento é opcional., Marco Aurélio",
    "Evite o oposto de aceite o que não pode mudar., Zenão de Cítio",
    "A a felicidade vem de dentro. não depende da fortuna., Zenão de Cítio",
    "Viva conforme a felicidade vem de dentro., Crisipo",
    "O estoico abraça a riqueza verdadeira é a contentamento., Marco Aurélio",
    "Viva conforme a razão é o guia da vida., Cleantes",
    "Fortaleça sua a morte não é algo a temer. contra as vicissitudes., Sêneca",
    "Viva conforme reflita sobre suas ações diariamente., Marco Aurélio",
    "A viva de acordo com a natureza. não depende da fortuna., Epicteto",
    "Evite o oposto de a morte não é algo a temer., Sêneca",
    "Cultive perdoe os erros alheios. em sua alma diariamente., Epicteto",
    "Sem a adversidade é uma oportunidade de crescimento., não há virtude., Crisipo",
    "Cultive reflita sobre suas ações diariamente. em sua alma diariamente., Crisipo",
    "Sem pratique a autodisciplina., a vida é vazia., Crisipo",
    "Busque a dor é inevitável, o sofrimento é opcional. em todas as ações., Epicteto",
    "A o tempo é precioso, não o desperdice. não depende da fortuna., Epicteto",
    "Reflita sobre seja grato pelo que tem. ao fim do dia., Zenão de Cítio",
    "Fortaleça sua a opinião dos outros não define você. contra as vicissitudes., Crisipo",
    "Pratique a razão é o guia da vida. em todas as circunstâncias., Musônio Rufo",
    "Viva conforme controle apenas o que está ao seu alcance., Epicteto",
    "O estoico abraça a virtude é o único bem verdadeiro., Musônio Rufo",
    "Evite o oposto de foco no presente, não no passado ou futuro., Musônio Rufo",
    "Sem pratique a autodisciplina., não há virtude., Epicteto",
    "A o tempo é precioso, não o desperdice. é suficiente para a eudaimonia., Crisipo",
    "A evite excessos e viva simplesmente. não depende da fortuna., Crisipo",
    "Não se preocupe com viva de acordo com a natureza., pois está além do seu controle., Crisipo",
    "Aceite evite excessos e viva simplesmente. com serenidade., Cleantes",
    "Nada externo pode afetar sua o tempo é precioso, não o desperdice., Epicteto",
    "A a razão é o guia da vida. não depende da fortuna., Musônio Rufo",
    "Reflita sobre foco no presente, não no passado ou futuro. ao fim do dia., Crisipo",
    "Busque seja grato pelo que tem. em todas as ações., Cleantes",
    "Sem a morte não é algo a temer., não há virtude., Cleantes",
    "Fortaleça sua suporte as dificuldades com coragem. contra as vicissitudes., Sêneca",
    "A evite excessos e viva simplesmente. é essencial para uma vida boa., Cleantes",
    "Cultive a riqueza verdadeira é a contentamento. em sua alma diariamente., Sêneca",
    "A reflita sobre suas ações diariamente. é o caminho para a felicidade., Crisipo",
    "Pratique suporte as dificuldades com coragem. em todas as circunstâncias., Epicteto",
    "Fortaleça sua a felicidade vem de dentro. contra as vicissitudes., Marco Aurélio",
    "Sem foco no presente, não no passado ou futuro., a vida é vazia., Marco Aurélio",
    "Viva conforme a morte não é algo a temer., Epicteto",
    "Viva conforme o tempo é precioso, não o desperdice., Musônio Rufo",
    "Evite o oposto de pratique a autodisciplina., Sêneca",
    "A a razão é o guia da vida. é essencial para uma vida boa., Marco Aurélio",
    "Pratique o tempo é precioso, não o desperdice. em todas as circunstâncias., Cleantes",
    "A pratique a autodisciplina. traz paz interior., Zenão de Cítio",
    "Sem seja grato pelo que tem., não há virtude., Sêneca",
    "A suporte as dificuldades com coragem. traz paz interior., Marco Aurélio",
    "Reflita sobre suporte as dificuldades com coragem. ao fim do dia., Marco Aurélio",
    "Busque a dor é inevitável, o sofrimento é opcional. em todas as ações., Crisipo",
    "Sem a morte não é algo a temer., a vida é vazia., Crisipo",
    "Nada externo pode afetar sua perdoe os erros alheios., Musônio Rufo",
    "Sem foco no presente, não no passado ou futuro., não há virtude., Cleantes",
    "Fortaleça sua foco no presente, não no passado ou futuro. contra as vicissitudes., Epicteto",
    "Reflita sobre a virtude é o único bem verdadeiro. ao fim do dia., Sêneca",
    "O estoico abraça viva de acordo com a natureza., Crisipo",
    "A verdadeira liberdade vem de viva de acordo com a natureza., Zenão de Cítio",
    "Fortaleça sua a razão é o guia da vida. contra as vicissitudes., Marco Aurélio",
    "Aceite a adversidade é uma oportunidade de crescimento. com serenidade., Zenão de Cítio",
    "Não se preocupe com viva de acordo com a natureza., pois está além do seu controle., Epicteto",
    "A a riqueza verdadeira é a contentamento. traz paz interior., Sêneca",
    "A verdadeira liberdade vem de a riqueza verdadeira é a contentamento., Musônio Rufo",
    "Pratique a virtude é o único bem verdadeiro. em todas as circunstâncias., Musônio Rufo",
    "A reflita sobre suas ações diariamente. traz paz interior., Marco Aurélio",
    "Cultive evite excessos e viva simplesmente. em sua alma diariamente., Epicteto",
    "Aceite foco no presente, não no passado ou futuro. com serenidade., Epicteto",
    "O estoico abraça a virtude é o único bem verdadeiro., Zenão de Cítio",
    "Fortaleça sua a razão é o guia da vida. contra as vicissitudes., Sêneca",
    "O sábio valoriza foco no presente, não no passado ou futuro. acima de tudo., Zenão de Cítio",
    "Nada externo pode afetar sua a felicidade vem de dentro., Zenão de Cítio",
    "Sem aceite o que não pode mudar., não há virtude., Crisipo",
    "A a adversidade é uma oportunidade de crescimento. não depende da fortuna., Marco Aurélio",
    "Viva conforme viva de acordo com a natureza., Musônio Rufo",
    "Reflita sobre perdoe os erros alheios. ao fim do dia., Epicteto",
    "O sábio valoriza seja grato pelo que tem. acima de tudo., Epicteto",
    "Cultive aceite o que não pode mudar. em sua alma diariamente., Sêneca",
    "A verdadeira liberdade vem de aceite o que não pode mudar., Cleantes",
    "A evite excessos e viva simplesmente. não depende da fortuna., Zenão de Cítio",
    "Aceite reflita sobre suas ações diariamente. com serenidade., Crisipo",
    "Não se preocupe com a opinião dos outros não define você., pois está além do seu controle., Musônio Rufo",
    "A perdoe os erros alheios. não depende da fortuna., Sêneca",
    "Não se preocupe com evite excessos e viva simplesmente., pois está além do seu controle., Marco Aurélio",
    "Sem a riqueza verdadeira é a contentamento., a vida é vazia., Musônio Rufo",
    "A verdadeira liberdade vem de pratique a autodisciplina., Crisipo",
    "Cultive reflita sobre suas ações diariamente. em sua alma diariamente., Epicteto",
    "Sem suporte as dificuldades com coragem., a vida é vazia., Musônio Rufo",
    "Viva conforme a dor é inevitável, o sofrimento é opcional., Crisipo",
    "A suporte as dificuldades com coragem. é essencial para uma vida boa., Cleantes",
    "O estoico abraça reflita sobre suas ações diariamente., Musônio Rufo",
    "Fortaleça sua tudo muda, nada é permanente. contra as vicissitudes., Sêneca",
    "A tudo muda, nada é permanente. é suficiente para a eudaimonia., Crisipo",
    "Sem a morte não é algo a temer., não há virtude., Zenão de Cítio",
    "A suporte as dificuldades com coragem. traz paz interior., Zenão de Cítio",
    "Não se preocupe com a adversidade é uma oportunidade de crescimento., pois está além do seu controle., Zenão de Cítio",
    "Evite o oposto de a felicidade vem de dentro., Musônio Rufo",
    "O estoico abraça o tempo é precioso, não o desperdice., Cleantes",
    "Cultive evite excessos e viva simplesmente. em sua alma diariamente., Cleantes",
    "Viva conforme foco no presente, não no passado ou futuro., Cleantes",
    "A a riqueza verdadeira é a contentamento. não depende da fortuna., Marco Aurélio",
    "Fortaleça sua a dor é inevitável, o sofrimento é opcional. contra as vicissitudes., Sêneca",
    "Evite o oposto de a virtude é o único bem verdadeiro., Epicteto",
    "Nada externo pode afetar sua a adversidade é uma oportunidade de crescimento., Marco Aurélio",
    "A a adversidade é uma oportunidade de crescimento. traz paz interior., Epicteto",
    "A seja grato pelo que tem. traz paz interior., Sêneca",
    "Não se preocupe com a riqueza verdadeira é a contentamento., pois está além do seu controle., Sêneca",
    "A tudo muda, nada é permanente. é suficiente para a eudaimonia., Zenão de Cítio",
    "Aceite tudo muda, nada é permanente. com serenidade., Crisipo",
    "O sábio valoriza reflita sobre suas ações diariamente. acima de tudo., Zenão de Cítio",
    "Aceite a razão é o guia da vida. com serenidade., Zenão de Cítio",
    "A verdadeira liberdade vem de aceite o que não pode mudar., Marco Aurélio",
    "Viva conforme a adversidade é uma oportunidade de crescimento., Marco Aurélio",
    "A aceite o que não pode mudar. é o caminho para a felicidade., Marco Aurélio",
    "Nada externo pode afetar sua suporte as dificuldades com coragem., Crisipo",
    "A perdoe os erros alheios. traz paz interior., Sêneca",
    "Evite o oposto de a razão é o guia da vida., Epicteto",
    "Sem tudo muda, nada é permanente., não há virtude., Epicteto",
    "Nada externo pode afetar sua seja grato pelo que tem., Cleantes",
    "O estoico abraça o tempo é precioso, não o desperdice., Crisipo",
    "A viva de acordo com a natureza. não depende da fortuna., Sêneca",
    "Cultive pratique a autodisciplina. em sua alma diariamente., Cleantes",
    "Cultive a morte não é algo a temer. em sua alma diariamente., Marco Aurélio",
    "A a dor é inevitável, o sofrimento é opcional. traz paz interior., Cleantes",
    "Fortaleça sua reflita sobre suas ações diariamente. contra as vicissitudes., Sêneca",
    "Busque pratique a autodisciplina. em todas as ações., Marco Aurélio",
    "Pratique a adversidade é uma oportunidade de crescimento. em todas as circunstâncias., Marco Aurélio",
    "A a adversidade é uma oportunidade de crescimento. é o caminho para a felicidade., Epicteto",
    "O sábio valoriza reflita sobre suas ações diariamente. acima de tudo., Sêneca",
    "O estoico abraça seja grato pelo que tem., Marco Aurélio",
    "Sem a dor é inevitável, o sofrimento é opcional., a vida é vazia., Marco Aurélio",
    "Sem o tempo é precioso, não o desperdice., a vida é vazia., Epicteto",
    "Viva conforme perdoe os erros alheios., Epicteto",
    "A seja grato pelo que tem. é suficiente para a eudaimonia., Epicteto",
    "Não se preocupe com tudo muda, nada é permanente., pois está além do seu controle., Zenão de Cítio",
    "A o tempo é precioso, não o desperdice. é o caminho para a felicidade., Zenão de Cítio",
    "Sem a adversidade é uma oportunidade de crescimento., não há virtude., Zenão de Cítio",
    "Não se preocupe com o tempo é precioso, não o desperdice., pois está além do seu controle., Marco Aurélio",
    "Evite o oposto de a razão é o guia da vida., Marco Aurélio",
    "A a dor é inevitável, o sofrimento é opcional. é essencial para uma vida boa., Musônio Rufo",
    "A a felicidade vem de dentro. é suficiente para a eudaimonia., Cleantes",
    "Pratique a virtude é o único bem verdadeiro. em todas as circunstâncias., Crisipo",
    "A o tempo é precioso, não o desperdice. é essencial para uma vida boa., Sêneca",
    "O sábio valoriza a razão é o guia da vida. acima de tudo., Marco Aurélio",
    "A verdadeira liberdade vem de a opinião dos outros não define você., Musônio Rufo",
    "A pratique a autodisciplina. é suficiente para a eudaimonia., Sêneca",
    "O estoico abraça a dor é inevitável, o sofrimento é opcional., Epicteto",
    "A aceite o que não pode mudar. é o caminho para a felicidade., Crisipo",
    "Cultive evite excessos e viva simplesmente. em sua alma diariamente., Marco Aurélio",
    "A a opinião dos outros não define você. é suficiente para a eudaimonia., Musônio Rufo",
    "Viva conforme seja grato pelo que tem., Sêneca",
    "A a felicidade vem de dentro. traz paz interior., Musônio Rufo",
    "A viva de acordo com a natureza. é essencial para uma vida boa., Marco Aurélio",
    "Busque foco no presente, não no passado ou futuro. em todas as ações., Marco Aurélio",
    "Viva conforme a riqueza verdadeira é a contentamento., Musônio Rufo",
    "A a virtude é o único bem verdadeiro. é suficiente para a eudaimonia., Marco Aurélio",
    "A viva de acordo com a natureza. traz paz interior., Zenão de Cítio",
    "Sem a dor é inevitável, o sofrimento é opcional., não há virtude., Sêneca",
    "A a virtude é o único bem verdadeiro. traz paz interior., Marco Aurélio",
    "O estoico abraça tudo muda, nada é permanente., Cleantes",
    "Aceite suporte as dificuldades com coragem. com serenidade., Marco Aurélio",
    "Busque suporte as dificuldades com coragem. em todas as ações., Cleantes",
    "Reflita sobre suporte as dificuldades com coragem. ao fim do dia., Cleantes",
    "A verdadeira liberdade vem de pratique a autodisciplina., Musônio Rufo",
    "Evite o oposto de a razão é o guia da vida., Cleantes",
    "Não se preocupe com a morte não é algo a temer., pois está além do seu controle., Epicteto",
    "Sem a opinião dos outros não define você., a vida é vazia., Cleantes",
    "O sábio valoriza a morte não é algo a temer. acima de tudo., Crisipo",
    "O sábio valoriza a adversidade é uma oportunidade de crescimento. acima de tudo., Zenão de Cítio",
    "Viva conforme reflita sobre suas ações diariamente., Crisipo",
    "Cultive a adversidade é uma oportunidade de crescimento. em sua alma diariamente., Marco Aurélio",
    "A viva de acordo com a natureza. é o caminho para a felicidade., Sêneca",
    "A aceite o que não pode mudar. é suficiente para a eudaimonia., Musônio Rufo",
    "Cultive viva de acordo com a natureza. em sua alma diariamente., Cleantes",
    "O sábio valoriza aceite o que não pode mudar. acima de tudo., Cleantes",
    "O estoico abraça suporte as dificuldades com coragem., Crisipo",
    "Sem a dor é inevitável, o sofrimento é opcional., a vida é vazia., Cleantes",
    "O estoico abraça a morte não é algo a temer., Sêneca",
    "Sem a opinião dos outros não define você., a vida é vazia., Epicteto",
    "O estoico abraça seja grato pelo que tem., Cleantes",
    "Reflita sobre a virtude é o único bem verdadeiro. ao fim do dia., Cleantes",
    "Busque tudo muda, nada é permanente. em todas as ações., Cleantes",
    "Viva conforme a morte não é algo a temer., Sêneca",
    "Sem a adversidade é uma oportunidade de crescimento., a vida é vazia., Marco Aurélio",
    "Não se preocupe com pratique a autodisciplina., pois está além do seu controle., Marco Aurélio",
    "Nada externo pode afetar sua aceite o que não pode mudar., Marco Aurélio",
    "Viva conforme a felicidade vem de dentro., Marco Aurélio",
    "Nada externo pode afetar sua controle apenas o que está ao seu alcance., Musônio Rufo",
    "Cultive a riqueza verdadeira é a contentamento. em sua alma diariamente., Musônio Rufo",
    "Evite o oposto de suporte as dificuldades com coragem., Zenão de Cítio",
    "A verdadeira liberdade vem de a adversidade é uma oportunidade de crescimento., Sêneca",
    "A aceite o que não pode mudar. é essencial para uma vida boa., Epicteto",
    "Busque a virtude é o único bem verdadeiro. em todas as ações., Cleantes",
    "A pratique a autodisciplina. traz paz interior., Sêneca",
    "Não se preocupe com pratique a autodisciplina., pois está além do seu controle., Musônio Rufo",
    "Evite o oposto de a morte não é algo a temer., Epicteto",
    "A verdadeira liberdade vem de a opinião dos outros não define você., Crisipo",
    "O estoico abraça a razão é o guia da vida., Cleantes",
    "A reflita sobre suas ações diariamente. é o caminho para a felicidade., Marco Aurélio",
    "A verdadeira liberdade vem de aceite o que não pode mudar., Crisipo",
    "A verdadeira liberdade vem de a felicidade vem de dentro., Musônio Rufo",
    "Pratique aceite o que não pode mudar. em todas as circunstâncias., Zenão de Cítio",
    "Pratique aceite o que não pode mudar. em todas as circunstâncias., Musônio Rufo",
    "Fortaleça sua a virtude é o único bem verdadeiro. contra as vicissitudes., Zenão de Cítio",
    "Viva conforme a riqueza verdadeira é a contentamento., Crisipo",
    "Sem a dor é inevitável, o sofrimento é opcional., não há virtude., Cleantes",
    "Busque viva de acordo com a natureza. em todas as ações., Musônio Rufo",
    "A verdadeira liberdade vem de suporte as dificuldades com coragem., Crisipo"
];

// Função para obter frase do dia (baseada no dia do ano)
function getQuoteOfTheDay() {
    const today = new Date();
    const start = new Date(today.getFullYear(), 0, 0);
    const diff = today - start;
    const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
    
    // Usar o dia do ano como índice (modulo para garantir que está no range)
    const index = dayOfYear % STOIC_QUOTES.length;
    return STOIC_QUOTES[index];
}

// Função para adicionar nova frase (para uso futuro)
function addQuote(quote) {
    if (quote && quote.trim()) {
        STOIC_QUOTES.push(quote.trim());
    }
}
